#!/bin/bash
# allocate-ports.sh — Assign unique ports for a worktree
#
# DTF standalone script — works from outside the Repo repo.
# Derives a port block from the ticket number, checks for collisions
# with other worktrees, and writes .env files.
#
# Usage:
#   bash ~/.claude/scripts/allocate-ports.sh <TICKET_ID>
#
# Port scheme:
#   Vite:  31xx  (e.g., PROJ-1657 -> 3174)
#   APIs:  base = 10000 + (slot * 100), then +1 through +8 per service
#
# Non-worktree users are NOT affected — all configs fall back to
# hardcoded defaults (500x) when no env vars are set.

set -euo pipefail

if [ "${1:-}" = "--help" ] || [ "${1:-}" = "-h" ] || [ "${1:-}" = "help" ]; then
    head -16 "$0" | tail -14
    exit 0
fi

TICKET_ID="${1:?Usage: $0 <TICKET_ID>}"

# --- Resolve paths from dtf-config.json or defaults ---
DTF_CONFIG="$HOME/.claude/dtf-config.json"
if [ -f "$DTF_CONFIG" ] && command -v jq &>/dev/null; then
    WORKTREE_PARENT=$(jq -r '.paths.worktreeParent // empty' "$DTF_CONFIG" 2>/dev/null)
    MEDHELP_ROOT=$(jq -r '.paths.monorepo // empty' "$DTF_CONFIG" 2>/dev/null)
fi
WORKTREE_PARENT="${WORKTREE_PARENT:-$HOME/Documents}"
MEDHELP_ROOT="${MEDHELP_ROOT:-$HOME/Documents/Repo}"

WORKTREE_DIR="$WORKTREE_PARENT/$TICKET_ID"

if [ ! -d "$WORKTREE_DIR" ]; then
    echo "ERROR: $WORKTREE_DIR does not exist" >&2
    exit 1
fi

# Extract numeric suffix from ticket ID (e.g., PROJ-1657 -> 1657)
TICKET_NUM=$(echo "$TICKET_ID" | grep -oE '[0-9]+$')
if [ -z "$TICKET_NUM" ]; then
    echo "ERROR: Cannot extract number from ticket ID '$TICKET_ID'" >&2
    exit 1
fi

# Derive slot: ticket_number mod 99 + 1 -> range 01-99 (wraps every 99 tickets)
SLOT=$(printf "%02d" $(( (TICKET_NUM % 99) + 1 )))

# Check if another worktree already uses this slot
collision_check() {
    local my_slot=$1
    for env_file in "$WORKTREE_PARENT"/*/.env; do
        [ -f "$env_file" ] || continue
        # Skip our own worktree and main repo
        [[ "$env_file" == "$WORKTREE_DIR/.env" ]] && continue
        [[ "$env_file" == "$MEDHELP_ROOT/.env" ]] && continue
        local other_slot
        other_slot=$(sed -n 's/^# Worktree:.*(slot \([0-9]*\)).*/\1/p' "$env_file" 2>/dev/null | head -n 1)
        if [ "$other_slot" = "$my_slot" ]; then
            echo "$env_file"
            return 0
        fi
    done
    return 1
}

# If collision, increment slot until free (wraps at 99)
ATTEMPTS=0
while conflicting_file=$(collision_check "$SLOT"); do
    ATTEMPTS=$((ATTEMPTS + 1))
    if [ "$ATTEMPTS" -gt 98 ]; then
        echo "ERROR: No free port slots available (99 worktrees!?)" >&2
        exit 1
    fi
    SLOT=$(printf "%02d" $(( (10#$SLOT % 99) + 1 )))
done

# Calculate ports from slot
VITE_PORT=$((3100 + 10#$SLOT))
API_BASE=$((10000 + 10#$SLOT * 100))
ServiceC_PORT=$((API_BASE + 1))
ABSENCE_PORT=$((API_BASE + 2))
STATISTICS_PORT=$((API_BASE + 3))
ServiceB_PORT=$((API_BASE + 5))
MESSENGER_PORT=$((API_BASE + 6))
ABSENCE_SYNC_PORT=$((API_BASE + 7))
ServiceC_SYNC_PORT=$((API_BASE + 8))

PROJECT_NAME="repo-$(echo "$TICKET_ID" | tr '[:upper:]' '[:lower:]')"

# --- Write root .env ---
cat > "$WORKTREE_DIR/.env" << EOF
# Worktree: $TICKET_ID (slot $SLOT)
# Auto-generated by allocate-ports.sh — do not edit manually.
# To regenerate: bash ~/.claude/scripts/allocate-ports.sh $TICKET_ID

# Project namespacing (affects container, volume, and network names)
COMPOSE_PROJECT_NAME=$PROJECT_NAME
MAIN_NETWORK=repo_repo-network

# API Services (worktree ports — unique per slot)
# Infrastructure ports (postgres, redis, etc.) use defaults from docker-compose.yml.
ServiceC_API_PORT=$ServiceC_PORT
ServiceC_SYNC_API_PORT=$ServiceC_SYNC_PORT
ABSENCE_API_PORT=$ABSENCE_PORT
ABSENCE_SYNC_API_PORT=$ABSENCE_SYNC_PORT
STATISTICS_API_PORT=$STATISTICS_PORT
ServiceB_API_PORT=$ServiceB_PORT
MESSENGER_API_PORT=$MESSENGER_PORT
EOF

# --- Write apps/web/.env.local ---
WEB_ENV="$WORKTREE_DIR/apps/web/.env.local"

# Copy base from main if no .env.local exists yet
if [ ! -f "$WEB_ENV" ] && [ -f "$MEDHELP_ROOT/apps/web/.env.local" ]; then
    cp "$MEDHELP_ROOT/apps/web/.env.local" "$WEB_ENV"
fi

# Strip any previous worktree port block (between markers), then re-append
if [ -f "$WEB_ENV" ]; then
    awk '/^# --- WORKTREE PORTS START ---$/{skip=1; next} /^# --- WORKTREE PORTS END ---$/{skip=0; next} !skip' \
        "$WEB_ENV" > "$WEB_ENV.tmp" && mv "$WEB_ENV.tmp" "$WEB_ENV"
fi

cat >> "$WEB_ENV" << EOF
# --- WORKTREE PORTS START ---
# Worktree-specific ports ($TICKET_ID, slot $SLOT)
VITE_DEV_PORT=$VITE_PORT

# API proxy targets — default to main stack (500x).
# Override ONLY the service(s) you rebuild from this worktree:
#   VITE_ServiceB_API_PORT=$ServiceB_PORT
VITE_ServiceC_API_PORT=5001
VITE_ABSENCE_API_PORT=5002
VITE_STATISTICS_API_PORT=5003
VITE_ServiceB_API_PORT=5005
VITE_MESSENGER_API_PORT=5006
# --- WORKTREE PORTS END ---
EOF

# --- Generate vite.config.worktree.mts (Phase 1 fallback) ---
# Standalone Vite config with worktree ports baked in.
# Used before the vite.config.mts env var PR merges.
VITE_WORKTREE_CONFIG="$WORKTREE_DIR/apps/web/vite.config.worktree.mts"

if [ -f "$WORKTREE_DIR/apps/web/vite.config.mts" ]; then
    sed \
        -e "s#process.env.VITE_DEV_PORT || \"3000\"#\"$VITE_PORT\"#g" \
        -e "s#process.env.VITE_ServiceC_API_PORT || \"5001\"#\"$ServiceC_PORT\"#g" \
        -e "s#process.env.VITE_ABSENCE_API_PORT || \"5002\"#\"$ABSENCE_PORT\"#g" \
        -e "s#process.env.VITE_STATISTICS_API_PORT || \"5003\"#\"$STATISTICS_PORT\"#g" \
        -e "s#process.env.VITE_ServiceB_API_PORT || \"5005\"#\"$ServiceB_PORT\"#g" \
        -e "s#process.env.VITE_MESSENGER_API_PORT || \"5006\"#\"$MESSENGER_PORT\"#g" \
        -e "s#port: 3000,#port: $VITE_PORT,#" \
        -e "s#\"http://localhost:5001\"#\"http://localhost:$ServiceC_PORT\"#g" \
        -e "s#\"http://localhost:5002\"#\"http://localhost:$ABSENCE_PORT\"#g" \
        -e "s#\"http://localhost:5003\"#\"http://localhost:$STATISTICS_PORT\"#g" \
        -e "s#\"http://localhost:5005\"#\"http://localhost:$ServiceB_PORT\"#g" \
        -e "s#\"http://localhost:5006\"#\"http://localhost:$MESSENGER_PORT\"#g" \
        "$WORKTREE_DIR/apps/web/vite.config.mts" > "$VITE_WORKTREE_CONFIG"
    echo "Generated vite.config.worktree.mts with worktree ports"
fi

echo ""
echo "Ports allocated for $TICKET_ID (slot $SLOT):"
echo ""
echo "  Vite dev server   http://localhost:$VITE_PORT"
echo "  ServiceC API           http://localhost:$ServiceC_PORT"
echo "  ServiceA API       http://localhost:$ABSENCE_PORT"
echo "  ServiceE API    http://localhost:$STATISTICS_PORT"
echo "  ServiceB API           http://localhost:$ServiceB_PORT"
echo "  ServiceD API     http://localhost:$MESSENGER_PORT"
echo ""
echo "To start the frontend with worktree ports:"
echo "  cd apps/web && npx vite --config vite.config.worktree.mts"
echo ""
echo "To proxy frontend through a rebuilt service, edit apps/web/.env.local:"
echo "  VITE_ServiceB_API_PORT=$ServiceB_PORT"
